id = "looped-themes"
name = "Looped"
description = "Looped Automation's themes for Zed"
version = "1.0.4"
schema_version = 1
authors = ["Ratul Maharaj <ratul@looped.sh>"]
repository = "https://github.com/loopedautomation/editor-themes"
